* Encoding: UTF-8.

DATASET ACTIVATE Jeu_de_données1.
COMPUTE poids=1 / ind_norm.
EXECUTE.

WEIGHT BY poids.

DESCRIPTIVES VARIABLES=hc2
  /STATISTICS=VARIANCE.


MEANS TABLES=hc2 BY sexe
  /CELLS=MEAN COUNT.

MEANS TABLES=hc2 BY milieu
  /CELLS=MEAN COUNT.

T-TEST GROUPS=milieu(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=hc2
  /CRITERIA=CI(.95).

T-TEST GROUPS=milieu(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=hc2
  /CRITERIA=CI(.95).
