# Generated by Django 5.2 on 2025-05-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oeuvre',
            fields=[
                ('id_oeuvre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
            ],
        ),
    ]
