# Generated by Django 5.2 on 2025-05-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oeuvre',
        ),
    ]
