# Generated by Django 5.2 on 2025-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksApp', '0002_delete_oeuvre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_oeuvre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
